---
- name: Install & configure the misc applications
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install CLI applications available on DNF
      ansible.builtin.dnf:
        name:
          - bat # cat with color
          - eza # better ls
          - fd-find # newer find
          - fzf # fuzzy finder
          - neovim # newer Vim
          - ripgrep # better grep
          - tmux # terminal multiplexer
          - wl-clipboard # for wl-copy
          - zoxide # better cd

    - name: Install bpython
      become: false
      community.general.pipx:
        name: bpython
        executable: /usr/bin/pipx
        state: present

    - name: Install Legcord (custom Discord client)
      ansible.builtin.dnf:
        name: legcord

    - name: Install Signal
      community.general.flatpak:
        name: org.signal.Signal

    - name: Install Kitty (terminal emulator)
      ansible.builtin.dnf:
        name: kitty
