---
- name: Run all the playbooks
  hosts: localhost
  connection: local
  gather_facts: false

- import_playbook: system.yml
- import_playbook: dotfiles.yml
- import_playbook: zsh.yml
- import_playbook: installers.yml
- import_playbook: video-acceleration.yml
- import_playbook: multimedia.yml
- import_playbook: apps.yml
- import_playbook: fonts.yml
- import_playbook: gnome.yml
- import_playbook: keyboard.yml
